#######################################################################################################################
## read proteome FASTA (human_proteome -> global_proteome, human_proteins -> global_protein_list)
#######################################################################################################################

## Create a list object from proteome FASTA file
global_proteome <- read_proteome(Proteome_File = Proteome_File_Directory) 
## there are 73,745 proteins in the canonical and 96,821 in the isoform database

#######################################################################################################################
## Create a list of "Parsed" protein sequences
#######################################################################################################################

global_protein_list <- parse_proteins(Proteome = global_proteome)

## Notes
# 
# 1. global_protein_list$ID is a vector of UniProt Accession Numbers
# 2. global_protein_list$Sequence is a vector of the corresponding sequences

#######################################################################################################################
## proteome parameters
#######################################################################################################################

proteome_size <- length(global_protein_list$ID)

#######################################################################################################################
## for generating a new global proteome with a different FASTA
#######################################################################################################################

## spike-in peptides
in_silico_tryptic_peptides_database <- generate_peptide_database(Proteome = global_proteome,
                                                                 Protein_Indices = c(), 
                                                                 Maximum_Missed_Cleavages = 2, 
                                                                 minimum_length = minimum_peptide_length,  
                                                                 maximum_length = maximum_peptide_length,
                                                                 remove_proline_sites = FALSE,
                                                                 methionine_peptides = TRUE)

## Notes

# 1. global_proteome is the output object generated by the read_proteome() function using the input FASTA file
# 2. Protein_Indices is a vector of all the proteins to be selected for in-silico digestion. If this is not supplied,  
#    all proteins in the supplied database are subjected to tryptic digestion.
# 3. Maximum_Missed_Cleavages is maximum number of missed cleavages allowed
# 4. minimum_length and maximum_length set the lower and upper bound on length of tryptic peptides, respectively
# 5. remove_proline_sites dictates whether cleavage sites followed by a proline are considered as cleavage sites or 
#    not.
# 6. methionine_peptides controls whether peptides at N-terminal side of the protein with the initial methionine 
#    removed are generated. Peptides without removing the N-terminal methionine are always generated, regarldless 
#    of the value of this parameter.
